Search overlay
SupernovaBrands/sandandsky-styleguides pull request #144
Opened 2021-09-06 04:58 UTC by teddymaulana

2021-09-06 05:07 UTC, foria requested changes

2021-09-06 05:07 UTC, foria commented on src/scss/compounds/_search-box.scss
> +      content: ' ';
this property usually is used with pseudo-classes and I think it's better to use it and not creating a new DOM element.
please check the indentation too

2021-09-07 02:35 UTC, teddymaulana commented on src/scss/compounds/_search-box.scss
> +      content: ' ';
yes I have tried using pseudo class, but since the the search box has overflow hidden, it doesn't works @foria

2021-09-08 09:34 UTC, foria approved these changes

2021-09-08 09:34 UTC, merged