Task/865cm0k00 Mobile Footer to be Shortened (Styleguide)
SupernovaBrands/sandandsky-styleguides pull request #304
Opened 2023-06-28 08:06 UTC by awais-supernovabrands

2023-06-28 09:12 UTC, foria requested changes

2023-06-28 09:12 UTC, foria commented on src/partials/sections/footer.hbs
> +		<small class="text-center d-block font-size-sm">Sand & Sky respectfully acknowledges the Traditional Owners of the land on which we operate, the Boon Wurrung and Woiwurrung (Wurundjeri) peoples of
We don't need small-font class if we are already using SMALL tag. They should have same properties in theory

2023-06-28 09:50 UTC, awais-supernovabrands commented on src/partials/sections/footer.hbs
> +		<small class="text-center d-block font-size-sm">Sand & Sky respectfully acknowledges the Traditional Owners of the land on which we operate, the Boon Wurrung and Woiwurrung (Wurundjeri) peoples of
ok let me remove them.

2023-07-03 06:17 UTC, foria approved these changes

2023-07-03 06:17 UTC, merged