Mobile Menu
SupernovaBrands/sandandsky-styleguides pull request #32
Opened 2021-06-22 05:56 UTC by teddymaulana

2021-06-23 06:07 UTC, foria requested changes

2021-06-23 06:07 UTC, foria commented on src/scss/compounds/_mobile-menu.scss
> +		}
empty

2021-06-23 06:07 UTC, foria commented on src/scss/compounds/_mobile-menu.scss
> +	}
there is a default function coming from bootstrap in order to open the mobile menu please check documentation

2021-06-23 06:07 UTC, foria commented on src/scss/compounds/_mobile-menu.scss
> +		}
empty

2021-06-23 06:07 UTC, foria commented on src/docs/compounds/mobile-menu.hbs
> +<!DOCTYPE html>
I cannot see it

2021-06-28 04:22 UTC, teddymaulana commented on src/docs/compounds/mobile-menu.hbs
> +<!DOCTYPE html>
what cannot you see? what should be fixed?

2021-06-28 04:24 UTC, teddymaulana commented on src/scss/compounds/_mobile-menu.scss
> +	}
this is not to open the mobile menu, this is to open submenu sequence, the function to open the mobile menu will be in the header later when integrate this branch

![Screen Shot 2021-06-28 at 11 23 13](https://user-images.githubusercontent.com/6266254/123580088-48a1d900-d803-11eb-9156-eea596da638d.png)

2021-06-29 02:06 UTC, foria requested changes

2021-06-29 02:06 UTC, foria commented on src/partials/compounds/mobile-menu.hbs
> +				<input type="radio" name="menu" id="back-to-menu-products" class="d-none">
please check the position of the Back button, the position between the 2nd and 3rd menu level is different, I think the position in the 3rd level is the one correct

2021-06-29 08:38 UTC, foria approved these changes

2021-06-29 08:41 UTC, merged