main header
SupernovaBrands/sandandsky-styleguides pull request #33
Opened 2021-06-22 06:35 UTC by teddymaulana

2021-06-30 02:51 UTC, foria requested changes
- it misses the search function (we must do a separate PR only for that)
- currency dropdown is wrong on desktop, it should have no click, positioned lower and with different chevron
- chevron when submenu is showed on desktop should change the orientation
- mobile menu should appear from left to right not in fade

2021-07-13 13:40 UTC, foria requested changes

2021-07-13 13:40 UTC, foria commented on src/js/modules/header.js
> +		$('body').toggleClass('offcanvas-active');
we can use the body class to also show the mobile-nav

2021-07-13 13:40 UTC, foria commented on src/partials/sections/header.hbs
> +							<a class="dropdown-item position-relative pt-2 pb-2 pr-5 active" href="#">United Kingdom (GBP)</a>
I think we don't need pos-relative on this item and pos-absolute on the after, it can b more simple if we just add negative margin-right on active item, what do you think?

2021-07-13 13:40 UTC, foria commented on src/partials/sections/header.hbs
> +					<a class="nav-link h4 m-0 font-weight-normal sni sni__search position-relative"></a>
please add hove effect on all first-level menu, including the one with chevron. color of text or svg must turn to primary-color. also order is Search first then Login, as on LIVE

2021-07-13 13:40 UTC, foria commented on src/scss/components/_nav.scss
> +	}
I don't see any use of this pseudo-class

2021-07-13 13:40 UTC, foria commented on src/scss/components/_nav.scss
> +			height: calc-em(33, 16);
it seems bigger than Live version

2021-07-13 13:40 UTC, foria commented on src/scss/components/_nav.scss
> +	}
please review syntax

2021-07-13 13:40 UTC, foria commented on src/scss/components/_nav.scss
> +			padding-right: $grid-gutter-width / 2;
we should use default bootstrap vars for this

2021-07-14 04:21 UTC, teddymaulana commented on src/partials/sections/header.hbs
> +							<a class="dropdown-item position-relative pt-2 pb-2 pr-5 active" href="#">United Kingdom (GBP)</a>
yes changed it to margin

2021-07-14 16:04 UTC, foria approved these changes

2021-07-14 16:04 UTC, foria commented on src/partials/sections/header.hbs
> +		<div class="container">
did you try to merge these 2 elements? bg-white can be applied on main-header

2021-07-16 05:56 UTC, foria approved these changes

2021-07-16 05:59 UTC, merged