Blog/breadcrumb
SupernovaBrands/sandandsky-styleguides pull request #46
Opened 2021-07-22 08:40 UTC by rizkiaaprilian

2021-07-22 09:22 UTC, foria requested changes

2021-07-22 09:22 UTC, foria commented on src/scss/components/_breadcrumb.scss
> +		@include font-size($font-size-base);
If on mobile it uses the default font size on desktop should be updated automatically since this rule is applied to the BODY as well, please check and let me know if it's not like that otherwise we should check the breakpoint for the BODY

2021-07-22 10:11 UTC, rizkiaaprilian commented on src/scss/components/_breadcrumb.scss
> +		@include font-size($font-size-base);
@foria I've checked on CE, mobile breadcrumb font size is smaller than body font size set from vars
$breadcrumb-font-size: calc-em(12); 

On large screen, the font size using default from breakpoint above.

2021-07-26 07:20 UTC, foria approved these changes

2021-07-26 07:20 UTC, merged