range info sections
SupernovaBrands/sandandsky-styleguides pull request #60
Opened 2021-08-02 02:12 UTC by pebiantara

2021-08-02 05:41 UTC, foria requested changes

2021-08-02 05:41 UTC, foria commented on src/docs/compounds/image-with-text.hbs
> +  </div>
why do we need this empty DIV? We should avoid it

2021-08-02 05:41 UTC, foria commented on src/docs/compounds/image-with-text.hbs
> +      </div><figcaption class="col-12 col-lg-6 p-0">
check syntax

2021-08-02 05:42 UTC, pebiantara commented on src/docs/compounds/image-with-text.hbs
> +  </div>
oh that is for divider, let me update

2021-08-02 08:31 UTC, pebiantara commented on src/docs/compounds/image-with-text.hbs
> +      </div><figcaption class="col-12 col-lg-6 p-0">
updated

2021-08-02 16:14 UTC, foria approved these changes
just replace the PNGs with SVGs

2021-08-03 12:42 UTC, pebiantara commented
closing and merge to https://github.com/SupernovaBrands/sandandsky-styleguides/pull/66

2021-08-03 12:42 UTC, closed without merging