sections range products and compounds collection banner
SupernovaBrands/sandandsky-styleguides pull request #62
Opened 2021-08-02 02:13 UTC by pebiantara

2021-08-02 05:32 UTC, foria requested changes
check for yotpo API as Rizki did for PDP

2021-08-02 05:32 UTC, foria commented on src/partials/compounds/product-card-secondary.hbs
> +          </div>
for yotpo on SS we already use the API successfully on PDP. Please integrate a clean code version and later we will apply API values on Shopify theme.

2021-08-02 05:32 UTC, foria commented on src/partials/html-head.hbs
>  <link rel="stylesheet" href="{{ cssUrl }}/yotpo.css">
we can probably not load this because of API

2021-08-02 05:32 UTC, foria commented on src/partials/html-head.hbs
> +<link rel="stylesheet" href="{{ cssUrl }}/yotpo_stars.css">
we can probably not load this because of API

2021-08-02 11:17 UTC, pebiantara commented on src/partials/html-head.hbs
> +<link rel="stylesheet" href="{{ cssUrl }}/yotpo_stars.css">
since i implemented with yotpo API, i don't need this file, so i removed it

2021-08-02 11:18 UTC, pebiantara commented on src/partials/html-head.hbs
>  <link rel="stylesheet" href="{{ cssUrl }}/yotpo.css">
this is not from me, but got confirmed from Rizki he still need this file

2021-08-02 11:20 UTC, pebiantara commented on src/partials/compounds/product-card-secondary.hbs
> +          </div>
i have integrated with yotpo api, removed above yotpo dom

2021-08-02 16:12 UTC, foria approved these changes
The only thing left is the tsw-badge png to replace with SVG

2021-08-03 12:42 UTC, pebiantara commented
closing and merge to https://github.com/SupernovaBrands/sandandsky-styleguides/pull/66

2021-08-03 12:42 UTC, closed without merging