Feature/range templates
SupernovaBrands/sandandsky-styleguides pull request #66
Opened 2021-08-03 12:41 UTC by pebiantara

Since PR
https://github.com/SupernovaBrands/sandandsky-styleguides/pull/62
https://github.com/SupernovaBrands/sandandsky-styleguides/pull/60
already approved and just need to wait for svg images, so i close those PR and merge with this PR

2021-08-04 16:19 UTC, foria requested changes
keep in mind consistency, remember that we must avoid 2 or more version of the same components, always. for any doubt just ask to me

2021-08-04 16:19 UTC, foria commented on src/partials/compounds/product-card-secondary.hbs
> +<figure class="product-card product-card--secondary {{ class }} text-center mb-4">
we don't need of this product card

2021-08-04 16:19 UTC, foria commented on src/scss/compounds/_collection-banner.scss
> +.collection-banner {
this banner is used on other pages besides the collection, please rename is as bottom-banner

2021-08-04 16:19 UTC, foria commented on src/scss/compounds/_image-with-text.scss
> +  img {
give a row space

2021-08-04 16:19 UTC, foria commented on src/scss/compounds/_image-with-text.scss
> +        margin-right: -60% !important;
why do we need !important?

2021-08-04 16:19 UTC, foria commented on src/scss/compounds/_product-card.scss
> +	&--secondary {
please remove it

2021-08-05 06:42 UTC, pebiantara commented on src/docs/compounds/product-card.hbs
> +		<h1>Product Card Secondary</h1>
removed secondary card

2021-08-05 06:43 UTC, pebiantara commented on src/scss/compounds/_image-with-text.scss
> +        margin-right: -60% !important;
because i have class mx-g there, but now i use mr-lg-n7 so i don't these margin anymore, i have updated
please check it out

2021-08-05 07:45 UTC, foria approved these changes

2021-08-05 07:56 UTC, merged