mega menu slide down animation
SupernovaBrands/sandandsky-styleguides pull request #68
Opened 2021-08-04 10:27 UTC by teddymaulana

2021-08-04 15:50 UTC, foria requested changes

2021-08-04 15:50 UTC, foria commented on src/scss/sections/_header.scss
> +	transition: all .5s ease;
I prefer we use transitions on selected property, the use of ALL use more browser resources since it creates an eventListener for all CSS properties for a single element

2021-08-05 03:11 UTC, teddymaulana commented on src/scss/sections/_header.scss
> +	transition: all .5s ease;
its updated

2021-08-05 06:00 UTC, foria approved these changes

2021-08-05 06:00 UTC, merged